# CI项目
name: QCA-ALL

# CI计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI权限
permissions: write-all

# CI任务
jobs:
  config:
    name: ${{ matrix.CONFIG }}

    # 只运行合法组合
    if: |
      (matrix.SOURCE == 'VIKINGYFY/immortalwrt' && matrix.BRANCH == 'main') ||
      (matrix.SOURCE == 'LiBwrt/openwrt-6.x' && matrix.BRANCH == 'k6.12-nss')

    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO, IPQ60XX-EMMC-WIFI-YES, IPQ60XX-EMMC-WIFI-NO, IPQ807X-WIFI-YES, IPQ807X-WIFI-NO]
        SOURCE: [VIKINGYFY/immortalwrt, LiBwrt/openwrt-6.x]
        BRANCH: [main, k6.12-nss]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
